---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: hbase
  name: hbase
spec:
  ports:
  - name: "60010"
    port: 60010
    targetPort: 60010
  selector:
    io.kompose.service: hbase
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase
  labels:
    app: hbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbase
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hbase
    spec:
      containers:
      - image: aaionap/hbase
        name: hbase
        ports:
        - containerPort: 60010
        - containerPort: 7199
          name: jmx
        env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HBASE_MASTER_OPTS
              value: "-Xms256m -Xmx6144m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Djava.rmi.server.hostname=$(POD_IP)"
           
        resources: {}
      restartPolicy: Always
     
status: {}



