apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs-datanode
spec:
  ports:
  - name: "50075"
    port: 50075
    targetPort: 50075
  selector:
    app: hdfs-datanode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs-datanode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-datanode
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      containers:
        - name: hdfs-datanode
          image: uhopper/hadoop-datanode:2.7.2
          env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local:50070
          ports:
          - containerPort: 50075
            name: fs
      restartPolicy: Always
