kind: Service
apiVersion: v1
metadata:
  name: wildfly-service
spec:
  selector:
    app: wildfly
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-deployment
  labels:
    app: wildfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wildfly
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
      - name: wildfly
        image: jboss/wildfly
        command: ["/opt/jboss/wildfly/bin/standalone.sh"]
        args: ["-b", "0.0.0.0", "-bmanagement" ,"0.0.0.0"]
        ports:
        - containerPort: 8080

