---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: lighttpd
  name: lighttpd
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: lighttpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighttpd-deployment
spec:
  selector:
    matchLabels:
      app: lighttpd
  replicas: 1
  template:
    metadata:
      labels:
        app: lighttpd
    spec:
      containers:
        - name: lighttpd
          image: lokeshopsramp/lighttpd
          ports:
            - containerPort: 80