apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
      - env:
        - name: NEO4J_dbms_connector_http_listen__address
          value: :7474
        - name: NEO4J_metrics_enabled
          value: "true"
        - name: NEO4J_metrics_jmx_enabled
          value: "true"
        - name: NEO4J_metrics_neo4j_counts_enabled
          value: "true"
        - name: NEO4J_metrics_neo4j_pagecache_enabled
          value: "true"
        - name: NEO4J_metrics_neo4j_tx_enabled
          value: "true"
        - name: NEO4J_metrics_prometheus_enabled
          value: "true"
        - name: NEO4J_metrics_prometheus_endpoint
          value: 0.0.0.0:2004
        image: neo4j:enterprise
        imagePullPolicy: ""
        name: neo4j
        ports:
        - containerPort: 7474
        - containerPort: 2007
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  ports:
  - name: "7474"
    port: 7474
    targetPort: 7474
  - name: "2007"
    port: 2007
    targetPort: 2007
  selector:
    io.kompose.service: neo4j
status:
  loadBalancer: {}

