---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
spec:
  ports:
  - name: "8983"
    port: 8983
    targetPort: 8983
  selector:
    io.kompose.service: solr
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: solr
    spec:
      containers:
      - image: solr
        name: solr
        ports:
        - containerPort: 8983
        - containerPort: 18983
        env:
            - name: ENABLE_REMOTE_JMX_OPTS
              value: "true"
            - name: RMI_PORT
              value: "18983"
            - name: REMOTE_JMX_OPTS
              value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=$RMI_PORT -Dcom.sun.management.jmxremote.rmi.port=$RMI_PORT"

        resources: {}
      restartPolicy: Always
status: {}

