apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: squid
  name: squid
spec:
  ports:
  - name: "3128"
    port: 3128
    targetPort: 3128
  selector:
    io.kompose.service: squid
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
  labels:
    name: squid-config
data:
  squid.conf: |-
    http_port 3128
    cache deny all
    connect_timeout 2 minutes
    shutdown_lifetime 3 seconds
    pconn_timeout 20 minutes    
    acl SSL_ports port 443
    #acl SSL_ports port 8443
    #acl SSL_ports port 3128
    acl Safe_ports port 443         # https
    #acl Safe_ports port 8443         # https
    acl Safe_ports port 3128         # https
    acl CONNECT method CONNECT    
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access allow all
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  labels:
    app: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: squid
    spec:
      containers:
      - image: sameersbn/squid:3.5.27-2
        name: squid
        ports:
        - containerPort: 3128
        volumeMounts:
         - name: squid-config-file
           mountPath: /etc/squid/squid.conf
           subPath: squid.conf
        resources: {}
      volumes:
      - name: squid-config-file
        configMap:
          name: squid-config
      restartPolicy: Always
status: {}


